name: Check for .gitignore files

on:
  pull_request:
    branches:
      - main

jobs:
  check_gitignore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for ignored files
        id: check_ignored_files
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Get the list of ignored files
          IGNORED_FILES=$(git check-ignore -n $CHANGED_FILES)

          # If there are any ignored files, exit with an error
          if [ -n "$IGNORED_FILES" ]; then
            echo "The following files are ignored by .gitignore:"
            echo "$IGNORED_FILES"
            exit 1
          else
            echo "No ignored files detected."
          fi

      - name: Output result
        if: steps.check_ignored_files.outcome == 'failure'
        run: echo "Please remove the ignored files from your commit."
